arch: amd64

language: python

jobs:
  include:
    - name: "Python 3.8 on Xenial Linux"
      os: linux
      python: 3.8
      dist: xenial
      addons:
        apt:
          packages:
            - python3-tk
      before_install:
        - virtualenv -p python twitter-sentiment
        - source twitter-sentiment/bin/activate
    - name: "Python 3.8 on macOS 10.15"
      os: osx
      osx_image: xcode11.6
      language: shell
      before_install:
        - python3 -m pip install virtualenv
        - python3 -m virtualenv twitter-sentiment
        - source twitter-sentiment/bin/activate
    - name: "Python 3.8 on Windows 10"
      os: windows
      language: shell
      env: PATH=/c/Python38:/c/Python38/Scripts:$PATH
      before_install:
        - choco install python --version 3.8.0
        - python -m pip install virtualenv
        - python -m virtualenv twitter-sentiment
        - source twitter-sentiment/Scripts/activate

before_install:
  - pip3 install --upgrade pip

install:
  - pip install python-dotenv
  - pip install tweepy
  - pip install coverage
  - pip install pytest
  - pip install pytest-cov
  - pip install codecov
  - pip install numpy
  - pip install pandas
  - pip install matplotlib

script:
  - ./tests/environment_variables.sh
  - coverage run -m pytest -v
  - coverage report -m
  - coverage xml

after_success:
  - bash <(curl -s https://codecov.io/bash) -f tests/coverage/coverage.xml

notifications:
  email:
    recipients:
      - "saurab.mish@gmail.com"
    on_success: never
    on_failure: always
